### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by rkarlsba** [beanz/celtic-knot-scad#1]
Seems this is getting rather old, but I just wonder if you could help out. It seems the following doesn't compile

square_corner(tile_width, rth, rrw, rgap);

since square_corner() only takes three arguments. The result is no good either, so something isn't right here.

Thanks in advance

roy

**Comment by beanz** [comment]
Thanks for mention this. These should have been just warnings - for me using version 2020.07.24 of openscad the test still rendered properly - but I've fixed them anyway.

Thanks again for reporting this issue.

**Comment by rkarlsba** [comment]
Thanks for the quick fix :) The rendering result was fine too. Actually, I just tried preview yesterday and the confusion of those warnings made me just sigh and rather do something else. Works fine now. So I'll go on with my hnefatafl board :)

**Comment by beanz** [comment]
Cool. I'd love to see the result but no problem if you can't or don't want to share it. I've not played hnefatafl since I was a teenager.

**Comment by rkarlsba** [comment]
Working on it - it'll be a library of sorts to make boards. Probably released under a CC license

**Comment by rkarlsba** [comment]
Sorry for pestering you, but I just wonder how I can use this to create something like the border of this https://en.wikipedia.org/wiki/Tafl_games#/media/File:ZHNEFA.jpg - it's a 2D model, made to be used on a lasercutter and I can't really understand your code here, how things link up etc.

Thanks in advance

roy

**Comment by rkarlsba** [comment]
If you want to look into the code etc, please email me on roy@karlsbakk.net. It's not out in the open yet, I just want to fix it a wee bit more first.

**Comment by rkarlsba** [comment]
One more question: The width of the lines in the tiles doesn't seem to be adjustable. Is that fixed based on the tile size or is there something I have missed?
